# **Numpy**

In [1]:
import numpy as np

In [2]:
# make ndarray

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# make array filled with 0

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# also can 1

arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# array filled with empty value

arr = np.empty((4,4))
print(arr) #can see leftover data

[[4.67296746e-307 1.69121096e-306 1.20160575e-306 6.23056670e-307]
 [2.22522597e-306 1.33511969e-306 1.37962320e-306 9.34604358e-307]
 [9.79101082e-307 1.78020576e-306 1.69119873e-306 2.22522868e-306]
 [1.24611809e-306 8.06632139e-308 1.60221208e-306 2.29178686e-312]]


In [9]:
# Get information of ndarray
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr.shape) #shape of array
print(arr.ndim) #dimension of array
print(arr.dtype) #data type of array

(2, 3)
2
int32


In [11]:
# Change data type in ndarray
arr_str = np.array(['1','2','3'])
print(arr_str.dtype)

<U1


In [12]:
arr_int = arr_str.astype(np.int64)
print(arr_int)
print(arr_int.dtype)

[1 2 3]
int64


In [13]:
arr_float = arr_int.astype(np.float64)
print(arr_float)
print(arr_float.dtype)

[1. 2. 3.]
float64


In [14]:
# Calculation of ndarray

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [17]:
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [19]:
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [21]:
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [22]:
print(arr1 / arr2)
print(np.divide(arr1, arr2))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [23]:
print(np.dot(arr1, arr2)) #matrix multiply

[[19 22]
 [43 50]]


In [25]:
# Slicing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr1 = arr[:2,1:]
print(arr1)

[[2 3]
 [5 6]]


In [26]:
# Index
print(arr[0,2])

3


In [27]:
# Mix Index and Slicing
print(arr[0,1:-1])

[2]


In [28]:
# Array index
print(arr[[0,1,2],[2,0,1]]) #get arr[0,2] [1,0] [2,1]

[3 4 8]


In [29]:
# Apply boolean to array
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [30]:
# Boolean index
print(arr[idx]) #get True element in ndarray

[4 5 6 7 8 9]


In [31]:
# Get data from file

redwine = np.loadtxt(fname='winequality-red.csv', delimiter=';', skiprows=1) #use ; to separate data, skip first line
print(redwine)


[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [33]:
# Basic statistics

print(redwine.sum())
print(redwine.mean())

152084.78194
7.926036165311652
