# **Numpy**

In [2]:
import numpy as np

In [3]:
# make ndarray

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# make array filled with 0

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# also can 1

arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# array filled with empty value

arr = np.empty((4,4))
print(arr) #can see leftover data

[[4.67296746e-307 1.69121096e-306 1.20160575e-306 6.23056670e-307]
 [2.22522597e-306 1.33511969e-306 1.37962320e-306 9.34604358e-307]
 [9.79101082e-307 1.78020576e-306 1.69119873e-306 2.22522868e-306]
 [1.24611809e-306 8.06632139e-308 1.60221208e-306 2.29178686e-312]]


In [8]:
# Get information of ndarray
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
print(arr.shape) #shape of array
print(arr.ndim) #dimension of array
print(arr.dtype) #data type of array

(2, 3)
2
int32


In [10]:
# Change data type in ndarray
arr_str = np.array(['1','2','3'])
print(arr_str.dtype)

<U1


In [11]:
arr_int = arr_str.astype(np.int64)
print(arr_int)
print(arr_int.dtype)

[1 2 3]
int64


In [12]:
arr_float = arr_int.astype(np.float64)
print(arr_float)
print(arr_float.dtype)

[1. 2. 3.]
float64


In [13]:
# Calculation of ndarray

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [14]:
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [15]:
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [16]:
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [17]:
print(arr1 / arr2)
print(np.divide(arr1, arr2))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
print(np.dot(arr1, arr2)) #matrix multiply

[[19 22]
 [43 50]]


In [19]:
# Slicing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr1 = arr[:2,1:]
print(arr1)

[[2 3]
 [5 6]]


In [20]:
# Index
print(arr[0,2])

3


In [21]:
# Mix Index and Slicing
print(arr[0,1:-1])

[2]


In [22]:
# Array index
print(arr[[0,1,2],[2,0,1]]) #get arr[0,2] [1,0] [2,1]

[3 4 8]


In [23]:
# Apply boolean to array
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [24]:
# Boolean index
print(arr[idx]) #get True element in ndarray

[4 5 6 7 8 9]


In [33]:
# Sort
arr = [5,3,7,1,6]

print(np.sort(arr,))

[1 3 5 6 7]


In [25]:
# Get data from file

redwine = np.loadtxt(fname='winequality-red.csv', delimiter=';', skiprows=1) #use ; to separate data, skip first line
print(redwine)


[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [31]:
# Basic statistics

print(redwine.sum()) #sum of all element
print(redwine.mean()) #average of all element

print(redwine[:,0])

152084.78194
7.926036165311652
[7.4 7.8 7.8 ... 6.3 5.9 6. ]


In [28]:
# Use axis

print(redwine.sum(axis=0))
print(redwine.mean(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]
[3.02952057e+00 3.20423261e-02 3.79237511e-02 1.98665392e+00
 2.21375732e-03 1.09346457e+02 1.08142564e+03 3.55980179e-06
 2.38202742e-02 2.87146470e-02 1.13493717e+00 6.51760540e-01]
[1.74055180e+00 1.79003704e-01 1.94740214e-01 1.40948711e+00
 4.70505826e-02 1.04568856e+01 3.28850367e+01 1.88674370e-03
 1.54338181e-01 1.69453967e-01 1.06533430e+00 8.07316877e-01]


In [30]:
# Other methods

print(redwine.min(axis=0))
print(redwine.max(axis=0))
print(redwine.var(axis=0)) #Variance
print(redwine.std(axis=0)) #Standard Deviation
print(np.median(redwine, axis=0))

[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
[3.02952057e+00 3.20423261e-02 3.79237511e-02 1.98665392e+00
 2.21375732e-03 1.09346457e+02 1.08142564e+03 3.55980179e-06
 2.38202742e-02 2.87146470e-02 1.13493717e+00 6.51760540e-01]
[1.74055180e+00 1.79003704e-01 1.94740214e-01 1.40948711e+00
 4.70505826e-02 1.04568856e+01 3.28850367e+01 1.88674370e-03
 1.54338181e-01 1.69453967e-01 1.06533430e+00 8.07316877e-01]
[ 7.9      0.52     0.26     2.2      0.079   14.      38.       0.99675
  3.31     0.62    10.2      6.     ]
